### ISSUE TITLE
Migrations from existing database

### ISSUE THREAD

**Issue by CawaKharkov** [za-web/l5-app#2]
Check if https://github.com/Xethron/migrations-generator working with L5. 
**If no - create own.**

**Comment by iillexial** [comment]
I don't understand what you want

**Comment by CawaKharkov** [comment]
I don't want to crate migrations by hands, in basic we need have a possibility to generate it from existing database structure.

**Comment by iillexial** [comment]
it should be artisan command?

**Comment by CawaKharkov** [comment]
Yes
